### Jekyll configuration



exclude: [
    README.md,
    nbproject
]

relative_permalinks: false



### user defined variables

# entry-type
# [ default, in-progress, deprecated, in-discussion, marked-to-delete ]
entry-type: default

# core url (used in Atom feed)
url: "http://php-de.github.io"

# global order id for unavailable orderId-Entries on guides
# the orderId must be between 0 and 25. the global definition of this value sort automaticly
# undefined entries after all defined entries.
orderId: 26

# page groups

groups:

    - name:   "Einführung"
      desc:   "Grundlegende Informationen zum Einstieg in PHP"
      path:   "/introduction"
      anchor: "introduction"

    - name:   "Allgemein"
      desc:   "Allgemeine Themen rund um PHP"
      path:   "/general"
      anchor: "general"

    - name:   "Entwicklungsumgebung"
      desc:   "Infos zu Editoren, IDE, Webserver, Tools, Komponenten, etc..."
      path:   "/dev-enviroment"
      anchor: "dev-enviroment"

    - name:   "Code-Optimierung"
      desc:   "Code-Optimierung von A bis Z."
      path:   "/code-optimizing"
      anchor: "code-optimizing"

    - name:   "Sicherheit"
      desc:   "Allgemeine Themen rund um die Sicherheit"
      path:   "/security"
      anchor: "security"

    - name:   "Debugging"
      desc:   "Auf Fehlersuche"
      path:   "/debugging"
      anchor: "debugging"

    - name:   "HTTP / Domain / URL / Requests / Dateisystem"
      desc:   "Informationen zu HTTP, URL, Requests und Dateisystem"
      path:   "/http-domain-url-filesystem"
      anchor: "http-domain-url-filesystem"

    - name:   "Datenbanken"
      desc:   "MySQL & Co."
      path:   "/database"
      anchor: "database"

    - name:   "E-Mail"
      desc:   "Wissenswertes über den Umgang mit E-Mail-Adressen, Mail-Servern, und Mailer-Klassen."
      path:   "/email"
      anchor: "email"

    - name:   "Formularverarbeitung"
      desc:   "Rund um die Erstellung, Verarbeitung, Validierung, etc. von Formularen"
      path:   "/form"
      anchor: "form"

    - name:   "Objektorientierte Programmierung (OOP)"
      desc:   "OOP unter PHP"
      path:   "/oop"
      anchor: "oop"

    - name:   "Standard Implementierungsansätze / Code-Snippets"
      desc:   "Gezielte Lösungsansätze und nützliche Code-Schnipsel für oft gefragtes"
      path:   "/implement-approach"
      anchor: "implement-approach"

    - name:   "Tutorials / Fertiglösungen"
      desc:   "Verschiedene Tutorials zu fertigen Implementierungen"
      path:   "/tutorials-solutions"
      anchor: "tutorials-solutions"
